name: Build Linux Release

on:
  push:
    tags:
      - 'pre-release0.0.1'
      - 'v*'

jobs:
  build-linux:
    name: Build Linux Binary
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
      
      - name: Build Linux binary
        run: |
          chmod +x ./build.sh
          ./build.sh --linux
      
      - name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/highlight-linux-amd64
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref, 'pre-release') }}
          generate_release_notes: true
